import { Text, View } from "react-native";
import { createStyleSheet, useStyles } from "react-native-unistyles";

type DropdownProps = {
  name: string;
};

export function Dropdown({ name = "Plop" }: DropdownProps) {
  const { styles } = useStyles(stylesheet);

  return (
    <View style={styles.container}>
      <Text style={styles.text}>This component was generated by {name}</Text>
    </View>
  );
}

const stylesheet = createStyleSheet((theme) => {
  return {
    container: {
      alignSelf: "center",
      flexDirection: "row",
      marginTop: 24,
    },
    text: {
      backgroundColor: theme.colors.typography,
      color: theme.colors.background,
      padding: 8,
    },
  };
});
