import { View } from "react-native";
import { createStyleSheet, useStyles } from "react-native-unistyles";

import { Text } from "../Text";

type CarouselProps = {
  /** The name of the person who generated this component */
  name: string;
};

/**
 * # Carousel
 *
 * @component
 *
 * @description A component that was generated by Plop
 *
 * @example
 *
 * ```tsx
 * <Carousel name="Plop" />
 * ```
 */
export function Carousel({ name = "Plop" }: CarouselProps) {
  const { styles } = useStyles(stylesheet);

  return (
    <View style={styles.container}>
      <Text style={styles.text}>This component was generated by {name}</Text>
    </View>
  );
}

const stylesheet = createStyleSheet((theme) => {
  return {
    container: {
      alignSelf: "center",
      flexDirection: "row",
      marginTop: 24,
    },
    text: {
      backgroundColor: theme.colors.typography,
      color: theme.colors.background,
      padding: 8,
    },
  };
});
