import { ComponentProps } from "react";
import { FlatList as RNFlatList } from "react-native";
import { useItemSeparatorComponent } from "../ItemSeparatorComponent";
import {
  defaultKeyExtractor,
  defaultRenderScrollComponent,
} from "../defaultListProps";

export type FlatListProps<ItemT> = ComponentProps<typeof RNFlatList<ItemT>> & {
  gap?: number;
};

/**
 * # FlatList
 *
 * @component
 *
 * @description A component that was generated by Plop
 *
 * @example
 *
 * ```tsx
 * <FlatList />
 * ```
 */
export function FlatList<ItemT = any>({
  ItemSeparatorComponent: ItemSeparatorComponentFromProp,
  contentContainerStyle,
  data,
  gap = 2,
  horizontal,
  keyExtractor = defaultKeyExtractor,
  renderItem,
  renderScrollComponent = defaultRenderScrollComponent,
  showsHorizontalScrollIndicator = true,
  showsVerticalScrollIndicator = true,
  ...rest
}: FlatListProps<ItemT>) {
  const ItemSeparatorComponent = useItemSeparatorComponent({
    gap,
    ItemSeparatorComponentFromProp,
  });

  return (
    <RNFlatList<ItemT>
      ItemSeparatorComponent={ItemSeparatorComponent}
      contentContainerStyle={contentContainerStyle}
      data={data}
      horizontal={horizontal}
      keyExtractor={keyExtractor}
      renderItem={renderItem}
      renderScrollComponent={renderScrollComponent}
      showsHorizontalScrollIndicator={showsHorizontalScrollIndicator}
      showsVerticalScrollIndicator={showsVerticalScrollIndicator}
      {...rest}
    />
  );
}
