import { useToggle } from "@common/hooks";
import { Eye, EyeOff } from "lucide-react-native";
import { forwardRef } from "react";
import { Pressable } from "react-native";
import { TextInput, TextInputProps, TextInputRef } from "../TextInput";

export type PasswordInputProps = TextInputProps;

/**
 * # PasswordInput
 *
 * @component
 *
 * @description A component that was generated by Plop
 *
 * @example
 *
 * ```tsx
 * <PasswordInput />
 * ```
 */
export const PasswordInput = forwardRef<TextInputRef, PasswordInputProps>(
  (props, ref) => {
    const [secureTextEntry, toggleSecureTextEntry] = useToggle(true);

    return (
      <TextInput
        ref={ref}
        right={
          <Pressable
            accessibilityRole="button"
            // TODO: move these styles outside
            style={{
              height: 39,
              aspectRatio: 1,
              justifyContent: "center",
              alignItems: "center",
            }}
            onPress={toggleSecureTextEntry}
          >
            {secureTextEntry ? <Eye size={24} /> : <EyeOff size={24} />}
          </Pressable>
        }
        {...props}
        secureTextEntry={secureTextEntry}
      />
    );
  },
);
