import { createStyleSheet, useStyles } from "react-native-unistyles";

import { TextInput, TextInputProps } from "../TextInput";
import { Eye, EyeOff } from "lucide-react-native";
import { useState } from "react";
import { Pressable } from "react-native";

type PasswordInputProps = TextInputProps;

/**
 * # PasswordInput
 *
 * @component
 *
 * @description A component that was generated by Plop
 *
 * @example
 *
 * ```tsx
 * <PasswordInput name="Plop" />
 * ```
 */
export function PasswordInput(props: PasswordInputProps) {
  // TODO: create useToggle component and use it here.
  const [secureTextEntry, setSecureTextEntry] = useState(true);
  const { styles } = useStyles(stylesheet);

  return (
    <TextInput
      right={
        <Pressable
          style={{
            height: 39,
            aspectRatio: 1,
            justifyContent: "center",
            alignItems: "center",
          }}
          onPress={() => {
            setSecureTextEntry(!secureTextEntry);
          }}>
          {secureTextEntry ? <Eye size={24} /> : <EyeOff size={24} />}
        </Pressable>
      }
      {...props}
      secureTextEntry={secureTextEntry}
    />
  );
}

const stylesheet = createStyleSheet((theme) => {
  return {
    container: {
      alignSelf: "center",
      flexDirection: "row",
      marginTop: 24,
    },
    text: {
      backgroundColor: theme.colors.typography,
      color: theme.colors.background,
      padding: 8,
    },
  };
});
