import { View } from "react-native";
import { createStyleSheet, useStyles } from "react-native-unistyles";

import { Portal } from "@gorhom/portal";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import { FullWindowOverlay } from "react-native-screens";
import { Text } from "../Text";

type NotificationProps = {
  /** The name of the person who generated this component */
  name?: string;
};

/**
 * # Notification
 *
 * @component
 *
 * @description A component that was generated by Plop
 *
 * @example
 *
 * ```tsx
 * <Notification name="Plop" />
 * ```
 */
// eslint-disable-next-line no-empty-pattern
export function Notification({ name = "Hello" }: NotificationProps) {
  const { styles } = useStyles(stylesheet);
  const { top } = useSafeAreaInsets();

  return (
    <Portal>
      <FullWindowOverlay>
        <View style={{ top }} pointerEvents="box-none">
          <View style={styles.notification}>
            <Text>{name}</Text>
          </View>
        </View>
      </FullWindowOverlay>
    </Portal>
  );
}

const stylesheet = createStyleSheet((theme) => {
  return {
    container: {
      alignSelf: "center",
      flexDirection: "row",
      marginTop: 24,
    },
    notification: {
      backgroundColor: "red",
      borderRadius: 16,
      padding: 24,
      margin: 8,
    },
    text: {
      backgroundColor: theme.colors.typography,
      color: theme.colors.background,
      padding: 8,
    },
  };
});
