import {
  StatusBar as ExpoStatusBar,
  StatusBarProps as ExpoStatusBarProps,
} from "expo-status-bar";
import { useTheme } from "@/modules/unistyles";
import { useMemo } from "react";
import { isIOS } from "@/utils/platform";

export type StatusBarProps = ExpoStatusBarProps & {
  isModal?: boolean;
};

/**
 * # StatusBar
 *
 * @component
 *
 * @description A component that was generated by Plop
 *
 * @example
 *
 * ```tsx
 * <StatusBar />
 * ```
 */
export function StatusBar({
  animated = true,
  hideTransitionAnimation = "fade",
  isModal,
  networkActivityIndicatorVisible = true,
  translucent = true,
}: StatusBarProps) {
  const { theme } = useTheme();
  const style = useMemo(() => {
    return theme === "system" ? "auto" : theme === "dark" ? "light" : "dark";
  }, [theme]);

  return (
    <ExpoStatusBar
      animated={animated}
      hideTransitionAnimation={hideTransitionAnimation}
      networkActivityIndicatorVisible={networkActivityIndicatorVisible}
      style={isModal && isIOS ? "light" : style}
      translucent={translucent}
    />
  );
}
